APP_NAME=italian_chemistry_cookbook

.PHONY: run web clean get doctor

run:
	flutter run

web:
	flutter run -d web-server

get:
	flutter pub get

clean:
	flutter clean
	flutter pub get

doctor:
	flutter doctor